### ISSUE TITLE
Sentry Error: Error Objects are not valid as a React child (found: object with keys {id, name}).

### ISSUE THREAD

**Issue by khamui** [liqd/zt-app#106]
**URL:** https://sentry.liqd.net/organizations/liqd/issues/1578/?query=is%3Aunresolved#exception
**user:** admin
**expected behaviour:** 
**behaviour:** sentry error
**important screensize:** any
**device & browser:** any
**Comment/Question:** it is a sentry error

First investigations:

1. In the sentry error right before the error is printed, there is a GET request to fetch an object
2. That object contains a property `categories` which holds an object `{id: ...., name: ...}`
3. The error seems to happen on rendering
4. Most probably this error is raised if `<Text></Text>` doesn't contain a string, e.g. `<Text>string</Text>`, but an object, e.g. `<Text>{object}</Text>`

Unfortunately this error was not reproducible on local.

**Comment by phillimorland** [comment]
think this has been resolved with refactor as doe not appear in list, will close for now
