### ISSUE TITLE
increase spacing when canceling the menu

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#125]
I think we could make the spacing here  higher, otherwise it might be to close to the bottom of the phone. 

![Bildschirmfoto 2021-09-13 um 11 49 17](https://user-images.githubusercontent.com/36957474/133063045-59e2ceae-90f6-4abb-bd72-32d9da815ca8.png)

**Comment by phillimorland** [comment]
NOTE: uses default element that have had no luck in customising
