### ISSUE TITLE
Log in: no error message when password is wrong

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#126]
![Bildschirmfoto 2021-09-13 um 11 50 45](https://user-images.githubusercontent.com/36957474/133063185-980e18d2-2326-48b2-9e10-e44a975470b2.png)

**Comment by phillimorland** [comment]
@lthueer @hello-kathi as we didn't have a design when we first did the login, i'm not sure we ever had a actual story for it, it was just a functionality we needed. Maybe this could go into a design implementation story for the login screen as there is now a design? https://app.zeplin.io/project/61cddc6825e4ee648e23f327/screen/60eea9a2b912f9ad6362d214

**Comment by lthueer** [comment]
@phillimorland you're right! There was no story so far for login but we have stories in the backlog for that. I will add a note there and close this issue now!
