### ISSUE TITLE
Long idea title issue

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#128]
URL: https://aplus-dev.liqd.net/teststadt-luca/projects/app-testing/

Note: Somehow my user name and the date "September" are connected and are very closely moved towards the voting buttons. This only seems to occur when a long username is selected

![Screenshot_20210913-121350_Expo Go](https://user-images.githubusercontent.com/36957474/133069192-23111fa8-ec5a-43ac-862c-10aec034df8c.jpg)

**Comment by khamui** [comment]
@lthueer i am not sure about what a good solution would be.

In case of collision of username, date and vote buttons, should we break them into new lines?
Regarding height of the tiles (list items), can they be different?

Shall we limit the number of chars for the title?

**Comment by lthueer** [comment]
@khamui that's a good question! I think limiting characters in frontend would be the best solution?
Breaking them into two lines could also work but that would need a different design for the list tiles, right? I my opinion the tiles should be always the same height.
What do you think @mcastro-lqd ?

**Comment by mcastro-lqd** [comment]
@lthueer @khamui In case of longer names I would rather break them in 2 lines Username + Date or use the abbreviation like on aplus (Sep.), but I don't know how would it be accessibilitywise with the readers, would that work?
