### ISSUE TITLE
Long category name issue

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#129]
**URL:** https://aplus-dev.liqd.net/teststadt-luca/projects/app-testing/

![Screenshot_20210913-123749_Expo Go](https://user-images.githubusercontent.com/36957474/133069881-5af594bf-7654-41ed-b254-26e6a2b638e4.jpg)

**Comment by phillimorland** [comment]
@mcastro-lqd how should we deal with this? would it be better to cut them off or limit it?

**Comment by mcastro-lqd** [comment]
@phillimorland @lthueer I think they should have a character limit in any case (web and app), otherwise they shouldn't be a label/category, right? 

Like around ~40 characters

**Comment by lthueer** [comment]
@mcastro-lqd @phillimorland I agree! Let's limit the amount of characters to 40

**Comment by Rineee** [comment]
@lthueer @mcastro-lqd @phillimorland Both labels and categories have a limit of 120 characters (in A4 :)) We cant really change that on DB level (unless we would truncate already existing ones, but that would affect other projects as well), so we still need a solution for showing possibly longer ones. 
For the app, we could limit the length in frontend? @fuzzylogic2000 ?

**Comment by mcastro-lqd** [comment]
@Rineee @lthueer @phillimorland @fuzzylogic2000 

Well, if we can't change them, then let's make it similar to aplus web then. https://zpl.io/29mgQ8W
