### ISSUE TITLE
#4647: image styling, position of image changes when uploading an image to an idea

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#147]
**URL:** 
**user:** 
**expected behaviour:** the image is always either left-justified or centered
**behaviour:** the image position changes according to way of uploading (camera=left; library=right)
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Camera
![Screenshot_20210921-164322_Expo Go](https://user-images.githubusercontent.com/36957474/134194415-d7ecb8fb-0be7-4ff9-8f49-3884d35a8bca.jpg)

Library
![Screenshot_20210921-164403_Expo Go](https://user-images.githubusercontent.com/36957474/134194427-5cfe58b0-7e53-43d2-a063-709f51bbb09e.jpg)

**Comment by fuzzylogic2000** [comment]
The image ends up where you have to click to take or add the image. I am not sure there is a (good) way to change it. @phillimorland ?

**Comment by phillimorland** [comment]
No but i'll make this note now for when one of us comes back to it.
Note: the image replaces the button that it was uploaded by as they are the same component, we could try adding logic to the styling to change component size or placement depending on if there is an image or not or something? no clue how though.

**Comment by phillimorland** [comment]
https://github.com/liqd/zt-app/issues/154
