### ISSUE TITLE
Comments: "read more" and "show answers" links broken

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/zt-app#149]
**URL:** 
**user:** 
**expected behaviour:** Lonc comments should be shortened and a read more link should be displayed. Comments with answers should not only show the link "show <number of> answers", but also open them when that link is clicked.
**behaviour:** Long comments are not shortened. The number of child comments and the link to see them are shown, but clicking does not have an effect.
**important screensize:**
**device & browser:** 
**Comment/Question:** 
https://github.com/liqd/zt-app/blob/e519ee28af605f8deaff75dcb46125a97126756d/containers/Comments/SubComment.js#L68
https://github.com/liqd/zt-app/blob/e519ee28af605f8deaff75dcb46125a97126756d/containers/Comments/Comment.js#L75
https://github.com/liqd/zt-app/blob/e519ee28af605f8deaff75dcb46125a97126756d/containers/Comments/Comment.js#L81

**Comment by Rineee** [comment]
Checked this, works now!
