### ISSUE TITLE
#4647 image cropping not working on ipad

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#153]
**URL:** 
**user:** 
**expected behaviour:** I can't select a specific area of an image
**behaviour:** I can select a specific area of an image
**important screensize:**
**device & browser:** ipad mini (5. Generation, 2019) Wi-Fi, Tablet,
64 GB, 7,9 Zoll, Space Grey
**Comment/Question:** 

No selection possible
![20210923_172046](https://user-images.githubusercontent.com/36957474/134536177-36828ba0-36dd-4004-8233-6a46cfa5564e.jpg)

**Comment by phillimorland** [comment]
@lthueer i'm not sure what you mean, is it the image cropping when adding an image to an idea?

**Comment by lthueer** [comment]
@phillimorland sorry for the bad image. Yes it is the cropping. Basically, you can't choose which area you want to select from the image and display it in an idea, and it just takes a default frame from the center.

**Comment by phillimorland** [comment]
this issue is blocked until this issue can be fixed https://github.com/liqd/zt-app/issues/206

**Comment by phillimorland** [comment]
@lthueer this should now be fixed with the image improvements we made, can you re-test?

**Comment by lthueer** [comment]
this works totally fine now!
