### ISSUE TITLE
idea detail view: three dots and back button incomplete

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#155]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** three dots disappear and back button is cut off slightly 
**important screensize:**
**device & browser:** APPLE iPad mini (5. Generation, 2019) Wi-Fi, Tablet,
64 GB, 7,9 Zoll, Space Grey
**Comment/Question:** 

![20210923_171128](https://user-images.githubusercontent.com/36957474/134537018-0cf90232-6baf-4159-89af-2dc9262c3a5e.jpg)

**Comment by phillimorland** [comment]
should be fixed
