### ISSUE TITLE
#4647 UI/UX Test - Idea Form: Image Styling and Scrolling

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/zt-app#158]
**device & browser:** *Android Emulator*
**Comment/Question:** *Both icons don't seem to be centralised and it looks like the line dividing the columns is thicker than the one around the table*
![Screenshot 2021-09-28 at 13 02 34](https://user-images.githubusercontent.com/59610786/135075945-4cf5d6d1-3b41-4b4e-a035-3cf4e7294fae.png)

Thanks!

**Comment by phillimorland** [comment]
linked https://github.com/liqd/zt-app/issues/154
