### ISSUE TITLE
[Android & iOS] Making PUT working with form-data --> Edit Idea

### ISSUE THREAD

**Issue by khamui** [liqd/zt-app#213]
**URL:** 
**user:** 
**expected behaviour:** After changing an image and submitting the form it should successfully make a PUT
**behaviour:** PUT currently does not work with form-data
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by Rineee** [comment]
@khamui This works now, right?

**Comment by khamui** [comment]
yes, that works.
