### ISSUE TITLE
Label styling: label is not selected when clicking on frame

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#225]
Is there any way to make the entire element clickable and not just the checkbox itself? Some people might find it annoying that the box is not checked when they click on the frame. Sometimes it can take up to 4 clicks for the box to be checked.

connected to story 5170

Tested on Android: Google Pixel 4a, and Samsung S9+

**Comment by phillimorland** [comment]
@lthueer were the label 'checkboxes' looking like in the design here? https://app.zeplin.io/project/61cddc6825e4ee648e23f327/screen/60f6ed8aed4b9e13de6f30ef because maybe the correct version wasn't released yet?

**Comment by lthueer** [comment]
@phillimorland no it's not. For me it's still the old checkboxes. I also tried logging in and out and different devices..
Is this still the current release for android? https://expo.dev/@liquiddemocracy/liqd-demo?release-channel=dev

**Comment by phillimorland** [comment]
@lthueer I can't access the dev version right now, or the main github one so not sure, @fuzzylogic2000 @goapunk has the most recent main been released to dev?

**Comment by goapunk** [comment]
I fixed the two issues I introduced, login should work again @phillimorland. @lthueer see my comment in mattermost

**Comment by lthueer** [comment]
perfect thank you @goapunk. Now it's there and all fine @phillimorland
