### ISSUE TITLE
Expo go not working on ios devices

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#232]
**URL:** 
**user:** 
**expected behaviour:** liqd-demo in expo go app can be opened
**behaviour:** liqd-demo can't be opened
**important screensize:**
**device & browser:** IPhone 11 Pro (15.2.1); Ipad mini (5th Generation) - 14.3
**Comment/Question:** 

Receiving the message: "incompatible update - the latest update uses a runtime version that is not compatible with Expo go. To continue, create a custom dev client (https://docs.expo.dev/development/getting-started/)"

Note: Expo go app and devices are updated to the newest versions

**Comment by goapunk** [comment]
looks like opening the link directly in the brower or using the regular camera app to scan the qr code still works if you are logged in, so we will stick with the current testing workflow I'd say.
