### ISSUE TITLE
project tile: date looks a bit lost

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#238]
**URL:** 
**user:** 
**expected behaviour:** date is displayed alligned
**behaviour:** date  is displayed in the middle of the tile
**important screensize:**
**device & browser:** Lenovo Yoga Tab 3 Plus, Android 11
**Comment/Question:** 

![IMG_20220126_143256](https://user-images.githubusercontent.com/36957474/151172415-5bdcb3c5-2752-48c7-aaae-3d0255c898df.jpg)

**Comment by phillimorland** [comment]
@mcastro-lqd should we be aiming to exactly replicate the designs on tablets and mobiles? in this case, the date positioning works on small screens but when more space is available like on a tablet it breaks design, we can set up stylesheets for tablets if neccesary.

**Comment by mcastro-lqd** [comment]
@phillimorland Wouldn't it stick to the right corner? I can also provide the screens for tablet.

**Comment by phillimorland** [comment]
currently we space the 3 elemenmts evenly across the tile ![Screenshot from 2022-01-27 09-15-35](https://user-images.githubusercontent.com/5871230/151319621-7861a478-4b01-4f63-8971-5f2223021b6a.png)

**Comment by lthueer** [comment]
@phillimorland yes exactly, it works on mobile, but on tablet it looks a bit weird. A stylesheet for tablets sounds legit to me, but you know best what works best!

**Comment by phillimorland** [comment]
@lthueer @mcastro-lqd this kind of needs a design or something or we should close it, maybe we can have a story for tablet styling tweaks or something?

**Comment by mcastro-lqd** [comment]
@phillimorland sorry, I missed that. Which tablet are we using to test them?

**Comment by phillimorland** [comment]
@mcastro-lqd I don't know but @lthueer should know?

**Comment by mcastro-lqd** [comment]
@phillimorland  but this was before the office break-in, is it still the same @lthueer?

**Comment by lthueer** [comment]
@phillimorland @mcastro-lqd I will have a look on my tablet at home next week. Currently, we don't have any tablets in the office (arriving soon). Not sure if it's still there

**Comment by lthueer** [comment]
Note: date looks fine on tablet now
