### ISSUE TITLE
Comment and vote  Icons are cut

### ISSUE THREAD

**Issue by hello-kathi** [liqd/zt-app#247]
**URL:** 
**user:** participant
**expected behaviour:** see the whole comment and vote icons
**behaviour:** comment and vote icon are cut
**important screensize:**
**device & browser:** iPhone xr ios 15.1
**Comment/Question:** 

Screenshot?
![photo_2022-01-28_08-51-28](https://user-images.githubusercontent.com/52459078/151508644-b3b0617d-bcb2-4cc9-92c7-461c6eafc952.jpg)

**Comment by phillimorland** [comment]
seems to be fixed on devices I tested on
