### ISSUE TITLE
error on submitting idea create form when no labels/categories

### ISSUE THREAD

**Issue by Rineee** [liqd/zt-app#248]
**URL:** 
**user:** 
**expected behaviour:** I can create or edit ideas in idea challenges without labels/categories
**behaviour:** error occurs and form is not submitted
**important screensize:**
**device & browser:** 
**Comment/Question:** `Warning: An unhandled error was caught from submitForm(), [TypeError: undefined is not an object (evaluating 'iter[Symbol.iterator]')]
at node_modules/formik/dist/formik.cjs.development.js:928:17 in useEventCallback$argument_0
`
happens when there are no categories

`JSON Parse error: Unrecognized token '<'`
`[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'response.statusCode')]
at containers/Ideas/IdeaCreate.js:119:12 in AsyncStorage.getItem.then.then$argument_0`
happens when no labels
Screenshot?

**Comment by phillimorland** [comment]
commit that broke it https://github.com/liqd/zt-app/commit/5cf574535f500ac25840c442a9dce60bb16d8fcf
