### ISSUE TITLE
comment on ideas: confusing error message wording when phase is not active

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#253]
**URL:** any project that is an app project and not active
**user:** participants
**expected behaviour:** error message indicates that phase is not active
**behaviour:** currently, it says "you don't have permission"
**important screensize:**
**device & browser:** 
**Comment/Question:** 

On a+ it's: "The currently active phase doesn't allow to comment." which makes it clearer I think.

Note: If it's easier to do all error messages later at once, we can also do it as part of a story. I just noticed now so that we don't forget.

**Comment by Rineee** [comment]
Actually the comment form should not be there, when the phase does not allow it and also the reply buttons should be disabled then (I am fixing that in my current PR). So that would solve that, right @lthueer ? But maybe an error message story would be good anyway!

**Comment by lthueer** [comment]
@Rineee ok cool, then this issue will be solved and I add an error message story to the backlog. Thank's
