### ISSUE TITLE
IdeaProject image styling broken / wrong size

### ISSUE THREAD

**Issue by goapunk** [liqd/zt-app#258]
**URL:** 
**user:** 
**expected behaviour:** Image is shown correctly
**behaviour:** Image is resized based on the size of the whole container, thus only showing a fraction of it if there's a lot of comments*
**important screensize:**
**device & browser:** any 
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
Is this still there after @phillimorland s redo?

**Comment by fuzzylogic2000** [comment]
will close this as the duplicate of #328 as @phillimorland s PR will fix that issue

**Comment by phillimorland** [comment]
i'll take a look, I think I only did the form image styling
