### ISSUE TITLE
idea create: image copyright checkbox is not validated

### ISSUE THREAD

**Issue by Rineee** [liqd/zt-app#260]
**URL:** 
**user:** 
**expected behaviour:** user cannot upload image unless copyright checkbox checked
**behaviour:** user can upload image even if copyright checkbox not checked
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by khamui** [comment]
submit button is enabled, but should not because of unchecked checkbox:
<img width="401" alt="Bildschirmfoto 2022-02-14 um 10 46 43" src="https://user-images.githubusercontent.com/52801593/153856785-4325c01f-811e-4e76-b27e-1fee4136a4c3.png">

**Comment by lthueer** [comment]
@fuzzylogic2000 yes, I agree! I'll add it to the milestone

**Comment by fuzzylogic2000** [comment]
@lthueer Thank you! Please also prioritize inside the milsestone so that we can start from the top.
