### ISSUE TITLE
[iOS] base-api: local backend for iOS

### ISSUE THREAD

**Issue by khamui** [liqd/zt-app#261]
**URL:** 
**user:** 
**expected behaviour:** setting LOCAL_API=true for iOS should use localhost
**behaviour:** setting LOCAL_API=true for iOS uses 10.0.0.2
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by phillimorland** [comment]
@khamui is this still relevant?
