### ISSUE TITLE
[Android & iOS] IdeaEdit: Adding imaging later is not possible

### ISSUE THREAD

**Issue by khamui** [liqd/zt-app#263]
**URL:** 
**user:** 
**expected behaviour:** Editing an idea in order to add an image should be able
**behaviour:** Editing an idea and adding an image after throws an error
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="404" alt="Bildschirmfoto 2022-02-14 um 10 47 45" src="https://user-images.githubusercontent.com/52801593/153856590-397b8b3d-ed34-4017-be45-6406b7d4277b.png">

**Comment by Rineee** [comment]
Note: works for me on both iOS and Android.. lets check in next app sprint @khamui!

**Comment by Rineee** [comment]
https://sentry.liqd.net/organizations/liqd/issues/2383/?alert_rule_id=30&alert_timestamp=1658332991459&alert_type=email&environment=production&project=30&referrer=alert_email

**Comment by khamui** [comment]
I just checked on the iPhone (Simulator) and figured out two things.

1.) Taking a photo on the iphone simulator is not possible, so I will add a commit to disable it for Apple Simulators
2.) The following screenshot shows an error that happens if picking images from the phone's library. But this error only happens for some of the "wallpaper" photos. I receive a 500 and i am not sure what is the problem there.

![Bildschirmfoto 2022-07-21 um 11 03 31](https://user-images.githubusercontent.com/52801593/180175662-deb0464c-4859-422d-ac18-cb27aa164ef1.png)

@Rineee maybe we can pair on this?

**Comment by khamui** [comment]
exact same issue happens also if using a real iphone device and taking a foto ⬆️
