### ISSUE TITLE
#6144 (organisation info): organisation name only changeable in django admin

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#317]
**URL:** https://aplus-dev.liqd.net/teststadt-imageview/
**user:** 
**expected behaviour:** organisation name can be changed by initiator in Dashboard
**behaviour:** organisation name is showing the name of the organisation from Django
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Usually the name of organisation is something like "amt-huettener-berge" and on a+ web the titel of the organisation is shown on the organisation page which is set by the initiator itself.
@Rineee would it be possible to change that?

**Comment by Rineee** [comment]
@lthueer Not sure, if I follow.. so there is the organisation name, that is set in Django Admin when adding the organisation and is also used for the slug, so the url of the organisation. The slug is set to the name that was added when creating the organisation and does not automatically change when changing the name later. I think this is why we also have the organisation title, that can be changed in the dashboard and is shown on the landing page of the organisation to the users.

So, your question would be to omit the title and instead show the name of the organisation and make that changeable in the dashboard? Due the connection to the url, I would not recommend that, I think. Maybe @fuzzylogic2000 also has an opinion on that :)

**Comment by fuzzylogic2000** [comment]
I am also not super sure what this issue is about. But my guess is: we should replace the organisation name by the organisation tiltle in the app?

**Comment by lthueer** [comment]
@Rineee @fuzzylogic2000 Ok, I think I might got it wrong and it's fine how it is. The confusion comes from that in a+ we usually put the url ending as a slug in the name of organisation, e.g. "amt-huettener-berge" and not as "Amt Hüttener Berge" which then is shown as the name of the organisation in the app. it would be nicer if the real name would be shown but i think it's just the difference how it's used by us...

**Comment by Rineee** [comment]
@lthueer Since the title of the organisation is not required in django admin, it might happen that it is not set. So, we would show the title if it is set and if not the name, would that be ok?

**Comment by lthueer** [comment]
@Rineee yes, perfect. Thank you
