### ISSUE TITLE
style clean up

### ISSUE THREAD

**Issue by philli-m** [liqd/zt-app#338]
- see if we can import repeated styles everywhere i.e. container answer: see TextSourceSans
- font sizes: as mobiles use different pixel densities the sizes of our fonts are off almost everywhere compare to what they should be, we need to fix this, possible using https://reactnative.dev/docs/pixelratio.html getFontScale
- once figured out font sizes use variables throughout app, not the multiplyer - already partially implemented

**Comment by phillimorland** [comment]
partial fix https://github.com/liqd/zt-app/pull/366

**Comment by lthueer** [comment]
@phillimorland, @mcastro-lqd you've mentioned recently that the text size in the app wouldn't be consistent with the design. To me it also seems a bit small tbh, maybe depending on the devices. Maybe we can fix this with the next app sprint? (fyi @hello-kathi)
