### ISSUE TITLE
Header background image ends too early

### ISSUE THREAD

**Issue by khamui** [liqd/zt-app#352]
**URL:** 
**user:** 
**expected behaviour:** header background image/color to be further to the bottom
**behaviour:** header background ends to early and is visible
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2022-07-21 um 08 37 12](https://user-images.githubusercontent.com/52801593/180146462-549cefad-aaa8-4c7e-bff4-08725ce0cf81.png)

**Comment by phillimorland** [comment]
fixed in https://github.com/liqd/zt-app/pull/366
