### ISSUE TITLE
#6214 UX/UI testing - report comments / #6207 UX/UI testing - report ideas

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/zt-app#355]
**device & browser:** *iOS 15.5*
**Comment:** *Here the styling is a little different than what was proposed. The button should be visible all the time too if possible.* 

![IMG_4697](https://user-images.githubusercontent.com/59610786/180225109-64b27687-4c50-4e9e-b64d-885e4be5ca33.PNG)

**Comment by phillimorland** [comment]
fixed with https://github.com/liqd/zt-app/pull/392
