### ISSUE TITLE
#6200 UX/UI testing - login with links to register and pw forgotten

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/zt-app#357]
**device & browser:** *iOS 15.5*
**Comment:** *I imagine you might have had discussed this during the past week, so just ignore if this is how it is supposed to be. 

There was the option to register in the app too right?
https://zpl.io/V0zPKOx*

**Comment by lthueer** [comment]
@mcastro-lqd yes, we discussed that and decided that for the beginning it's more important to have a nice login screen. Registration will follow later. Closing this issue as we have stories in the backlog for that.
