### ISSUE TITLE
#6185 UX/UI testing - show richtext for project info and result

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/zt-app#358]
**device & browser:** *iOS 15.5*
**Comment:** *Here I don't get how it works cause this organisation is displayed differently on the app than the actual information on desktop. The contact is also different.* 

Desktop:
<img width="834" alt="Screenshot 2022-07-21 at 15 41 15" src="https://user-images.githubusercontent.com/59610786/180228422-eb78c966-fa18-4342-be9b-7f79b2e2d86b.png">

App:
![IMG_4700](https://user-images.githubusercontent.com/59610786/180228567-9ad07d58-3a93-4d59-a430-cf54f191940b.PNG)
![IMG_4699](https://user-images.githubusercontent.com/59610786/180228592-7b24802e-d77d-4848-ad6e-a92a4417ec2f.jpg)

**Comment by lthueer** [comment]
@mcastro-lqd this might be an ios issue thing, testing on android the information is displayed as on the web. See for example here: https://aplus-dev.liqd.net/teststadt-luca/projects/app-testing/

**Comment by phillimorland** [comment]
this appears to be working so will close
