### ISSUE TITLE
#6185 UX/UI testing - Project info and result: remove circle around collapsible button

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/zt-app#359]
**device & browser:** *iOS 15.5*
**Comment:** *Do we have any control of this collapsable element styling?*

<img width="570" alt="Screenshot 2022-07-21 at 15 44 55" src="https://user-images.githubusercontent.com/59610786/180228852-8075f09d-bef9-4d9e-8545-f3fea0ba29a7.png">

**Comment by khamui** [comment]
yes, we can style them as we want. not sure about animations (sliding up and down) though.
we tried to style it as it appears on the web.

**Comment by philli-m** [comment]
@hello-kathi @lthueer @mcastro-lqd I didn't find a design when checking screens so don't know what to do here?

**Comment by lthueer** [comment]
@philli-m I think the problem here is that the cross has a circle around it, which is not the case with a+ web. What do you think should be changed, @mcastro-lqd?

**Comment by fuzzylogic2000** [comment]
@mcastro-lqd Is that what we should do? Remove the circle?

**Comment by Rineee** [comment]
@mcastro-lqd Sorry for bothering you again, but could you have a look here?

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 @philli-m Actually I never did that, that's why there is no screen. It was implemented directly via pm and dev. Personally, I think it's better without the circle cause we don't have something like that anywhere else on aplus.
