### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/zt-app#360]
**device & browser:** *iOS 15.5*
**Comment:** *I think a crucial element to fix for the app now, would be this Back button. I remember that it used to work, but it seems broken now. Also, if possible I would try to add a slide to the right function which would add a different way of going back to the screen before. Currently I'm having to quit the app and open again in order to see a different project/idea. Thank you so much* 

<img width="430" alt="Screenshot 2022-07-21 at 15 48 58" src="https://user-images.githubusercontent.com/59610786/180229734-1ef855dd-9a8e-498d-85b6-cf4c6f2ba42d.png">
<img width="1159" alt="Screenshot 2022-07-21 at 15 51 24" src="https://user-images.githubusercontent.com/59610786/180230322-dcd64be6-4167-48b9-a4fe-98df380f8eae.png">

**Comment by phillimorland** [comment]
duplicate https://github.com/liqd/zt-app/issues/350
