### ISSUE TITLE
move getToken to BaseApi

### ISSUE THREAD

**Issue by Rineee** [liqd/zt-app#370]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 
We now need the token authentication for every request we are making, so instead of getting the token in the fetch methods, we should move that to BaseApi 

Screenshot?

**Comment by hello-kathi** [comment]
@Rineee is that important for testing the app? Then I would put it into the milestone for the next sprint.

**Comment by Rineee** [comment]
It is not important for testing, more of a refactor thing, but still would be good if we did that, so if there is place for it in the milestone, it would be good :)
