### ISSUE TITLE
iOS: Expo Go version incompatible with devserver

### ISSUE THREAD

**Issue by khamui** [liqd/zt-app#381]
**URL:** 
**user:** 
**expected behaviour:** using physical iphone to open the app with account works and shows the app
**behaviour:** error below (screenshot) is popping up
**important screensize:**
**device & browser:** 
**Comment/Question:** 

![IMG_1836](https://user-images.githubusercontent.com/52801593/181506273-c9a788b9-3f2b-4ae8-87a2-e50980653290.PNG)

The link shown there leads to the following page:
https://docs.expo.dev/development/getting-started/

**Comment by goapunk** [comment]
Following the steps here works for me: https://wiki.liqd.net/publishing_apps Open the link in your browser and scan the Qr Code with your regular iphone camera, then click on `open in expo go`

**Comment by lthueer** [comment]
@goapunk @khamui for me it works when scanning the QR code with the ios camera but not when being logged in. Thank you!

**Comment by phillimorland** [comment]
will close as working
