### ISSUE TITLE
Creating ideas: idea description doesnot show text input

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#389]
**URL:** https://aplus-dev.liqd.net/teststadt-luca/ideas/2022-00702/
**user:** 
**expected behaviour:** user can see text input
**behaviour:** when text is entered it's not shown
**important screensize:**
**device & browser:** tested on android and ios
**Comment/Question:** 

![Screenshot_20220804-110858](https://user-images.githubusercontent.com/36957474/182810894-a0081f75-f0dc-4897-b08d-f64a7cbbd871.png)

**Comment by phillimorland** [comment]
fixed with https://github.com/liqd/zt-app/pull/392
