### ISSUE TITLE
Android scroll on category dropdown not scrolling android

### ISSUE THREAD

**Issue by philli-m** [liqd/zt-app#394]
When there are over 5 categories the dropdown list doesn't show them and it won't scroll:
https://aplus-dev.liqd.net/phillitopictest-org/projects/app-with-categories-and-labels/

NOTE: assumed it was the addition of `KeyboardScroll` but after removal the dropdown scroll is still broken.

**Comment by philli-m** [comment]
on further testing the scroll work on IOS but not on android 
ADDITIONAL: 
- IOS does not save the selected category 
- submit button not fixed to bottom of screen both os

**Comment by khamui** [comment]
fixed
