### ISSUE TITLE
#6234: adding profile pic not working

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#395]
**URL:** 
**user:** all
**expected behaviour:** profile picture is uploaded
**behaviour:** profile picture is not uploaded
**important screensize:**
**device & browser:** google pixel 4a (Android 12) / Iphone 6s (ios 15.5)
**Comment/Question:** 
it says that the image is uploaded but once you click again in "edit profile" the profile picture is not updated and the image turns blue

**Comment by phillimorland** [comment]
@lthueer and when you go back to your profile screen?

**Comment by goapunk** [comment]
this should be fixed along with #396

**Comment by lthueer** [comment]
works now
