### ISSUE TITLE
#6233 profile picture is not shown in app

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#396]
**URL:** 
**user:** all
**expected behaviour:** profile picture is shown in profile overview
**behaviour:** profile picture is not shown in profile overview
**important screensize:**
**device & browser:** google pixel 4a (Android 12) / Iphone 6s (ios 15.5)
**Comment/Question:** 
No profile picture is shown, although one is set in a+ web
connected to issue #395 
odd discovery: while the following issue occurs on iphone 11 pro: #390, the profile pic is shown correctly. Not for the devices mentioned above..

![Screenshot_20220808-150608](https://user-images.githubusercontent.com/36957474/183425175-2d11a10e-fa0e-475d-8a89-456ab50198b0.png)

**Comment by goapunk** [comment]
should be solved with https://github.com/liqd/adhocracy-plus/pull/2017 I think

**Comment by goapunk** [comment]
@lthueer fixed for me now

**Comment by lthueer** [comment]
Works for me without any problems
