### ISSUE TITLE
Child comment can't be deleted

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#402]
**URL:** https://aplus-dev.liqd.net/teststadt/ideas/2022-00732/
**user:** participant, initiator
**expected behaviour:** childcomment can be deleted
**behaviour:** childcomment can't be deleted if it's a childcomment to another users comment. For childcommenting own comments deletion works
**important screensize:**
**device & browser:** 
**Comment/Question:**

**Comment by phillimorland** [comment]
@lthueer just tested on iphone emulator and it seems to work, can you check again and see if its device specific? 
location of deleted comment https://aplus-dev.liqd.net/teststadt/ideas/2022-00731/?comment=866

**Comment by lthueer** [comment]
@phillimorland if I am logged in as an admin it works but not when I am logged in with a normal user account, then the issue is still there. Tested it on android emulator and device

**Comment by Rineee** [comment]
Note: this sounds like a permissions issue (maybe permission object is the parent comment and not the comment itself?)

**Comment by lthueer** [comment]
Note: Tested as normal participant and initiator and it doesnot work to delete your own child-comment to another user's comment

**Comment by phillimorland** [comment]
@lthueer awesome permissions stuff is way better :)
