### ISSUE TITLE
ios: idea challenge submit button visible during voting phase 

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#403]
**URL:** 
**user:** 
**expected behaviour:** submit button not visible
**behaviour:** submit button still visible when second phase (voting) has started
**important screensize:**
**device & browser:** only on ios, for android it works
**Comment/Question:**

**Comment by Rineee** [comment]
@lthueer I just checked this and the submit button does not show for me during rating phase. Can you please double check (also that you are not logged in as admin or moderator)?

**Comment by lthueer** [comment]
@Rineee this issue only happens on ios apparently, we found out during user testing

**Comment by Rineee** [comment]
@lthueer Yes, I know, I checked it with my iphone and could not reproduce with a normal user account. Did you check it again?

**Comment by lthueer** [comment]
@Rineee I need to test with one of the iphones in the office next week, and will let you know
