### ISSUE TITLE
In voting phase, deletion of ideas and comments not possible

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#404]
**URL:** https://aplus-dev.liqd.net/teststadt/projects/wettbewerb-der-ideen-in-musterstadt/
**user:** all
**expected behaviour:** in voting phase ideas and comments can be deleted
**behaviour:** when voting phase starts ideas and comments can't be deleted
**important screensize:**
**device & browser:** 
**Comment/Question:** 

- Should deletion always be possible not matter which phase it is?
- editing shouldn't be enabled when voting phase has started

**Comment by Rineee** [comment]
@lthueer @hello-kathi This is actually not really an issue, but our implemented behaviour in Aplus: In collect phase users can add, change and delete ideas and comments, whereas in rating phase, users can only rate and neither add, change nor delete ideas or comments. We can discuss this behaviour and change it, but I think this would rather be a small story than an issue. What do you think?

**Comment by fuzzylogic2000** [comment]
This would also need to be talked about and done in a+.
Will remove it from the milestone. :woman_shrugging:

**Comment by lthueer** [comment]
@fuzzylogic2000 @Rineee alright! Maybe this is sth. to be changed in a+ then as it lead to confusion during user testing. I think it would make sense to still being able to delete comments and ideas but not to edit them (because it's too late and about rating). No high prio, but I'll take that to the a+ backlog

**Comment by Rineee** [comment]
@lthueer I will close this as it needs to be fixed in Aplus, ok?
