### ISSUE TITLE
buttons performance

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#410]
**URL:** 
**user:** 
**expected behaviour:** buttons (e.g. submit idea) doesnot need to be clicked more than once before they react
**behaviour:** sometimes you need to click a button several times
**important screensize:**
**device & browser:** doesn't seem to be the case for specific devices, but happens from time to time
**Comment/Question:** 
- e.g. when updating the profile image on ios and click the save button, you need to click it more than once to make it work (tested on ipad mini)

**Comment by khamui** [comment]
To whom picking this. Maybe it is fixed by #416 (profile image changing). If not in any case it depends on that PR.

**Comment by fuzzylogic2000** [comment]
@lthueer Could you pleas test if we fixed this with fixing the image upload?

**Comment by lthueer** [comment]
@fuzzylogic2000 @khamui @hello-kathi no it's not! For me sometimes it happens that I have to click very strong on the submit and other buttons (back, comment etc) in order to make it work. An easy click doesn't work.. (tested on google pixel 4a)

**Comment by fuzzylogic2000** [comment]
let's do this with the loading in story 7150

**Comment by philli-m** [comment]
@lthueer have you ever experienced this issue on an emulator or was it just with device testing? I am having trouble replicating it

**Comment by lthueer** [comment]
@philli-m, I've only noticed on real devices, ios and android

**Comment by lthueer** [comment]
@philli-m looks good to me, that's way better. Thank you!
