### ISSUE TITLE
Dropdown and scroll view not compatible 

### ISSUE THREAD

**Issue by phillimorland** [liqd/zt-app#42]
error: 
`VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.`

Also IOS dropdown appears behind checkbox element

**Comment by fuzzylogic2000** [comment]
@khamui And I will mention you in every issue. :woman_shrugging:

**Comment by phillimorland** [comment]
closed in favour of duplicate https://github.com/liqd/zt-app/issues/189
