### ISSUE TITLE
#7152: Wrong translation in the description of an ended participation

### ISSUE THREAD

**Issue by SandisStudi** [liqd/zt-app#447]
**URL:** https://aplus-dev.liqd.net/teststadt-luca/
**user:** reg. User
**expected behaviour:** everything is translated right
**behaviour:** In the description of an ended phase it says ""Beteiligung beendet. Ergebnis lesen." It should be better "Beteiligung beendet. Ergebnis ansehen"

Screenshot?
![IMG_9388](https://user-images.githubusercontent.com/113611764/227197605-b7a4b14d-4cc3-4dbe-902c-17bb58d1240b.jpg)

**Comment by Rineee** [comment]
@SandisStudi @lthueer We get this string from Aplus, where we also use it on the tiles. If you want to change the wording, please open an issue there!
