### ISSUE TITLE
#7152: Language Issues german phrases when preferring english language 

### ISSUE THREAD

**Issue by SandisStudi** [liqd/zt-app#450]
**URL:** https://aplus-dev.liqd.net/phillitopictest-org/projects/app-project-2/
**user:** 
**expected behaviour:** when using the app on english i want that everything is written on english except user input 
**behaviour:** there are german phrases even when using app on english 
**device & browser:** IPhone XS

- Phrases for remaining time or if the participatory project has ended/ not started yet are on german ( first Screenshot)
- Date of comments is still shown german (second screenshot)
- Date of participatory phases are still shown on german (third screenshot)

![IMG_9396](https://user-images.githubusercontent.com/113611764/227226953-0519ea6f-d190-4dde-b23e-1b3bee498172.jpg)
![IMG_9395](https://user-images.githubusercontent.com/113611764/227227010-dafd505c-f3ac-4791-9720-546f801de8f5.jpg)

![IMG_9400](https://user-images.githubusercontent.com/113611764/227227495-2643a2ee-d99b-411a-9ee0-987eeef3a0bd.jpg)

**Comment by Rineee** [comment]
I tried to remove the language from Async Storage on login, but that did not work for iOS on real device.. Since Im off on Monday, unassigning for now..

**Comment by fuzzylogic2000** [comment]
These are the strings coming from the backend that are not updated after language change after login when I got that right. @Rineee
