### ISSUE TITLE
navigation: back button invisible on white background image

### ISSUE THREAD

**Issue by goapunk** [liqd/zt-app#47]
The back button is drawn on top of the project image, if the image has the same color as the back button the button becomes almost invisible.

**Comment by phillimorland** [comment]
@mcastro-lqd as we do not have ability to tell the colour of the image do you have a suggestion of a design solution for this?

**Comment by mcastro-lqd** [comment]
@phillimorland In the file there is a gradient on the image so even when its white on white, its readable, an example would be the Instagram Shops where the title of the Collections are on top of the image too or Facebook Stories has the same think. 

![IMG_8747](https://user-images.githubusercontent.com/59610786/147769815-b668ca3d-6166-4eb1-b79f-5e3a2b91341d.PNG)

**Comment by phillimorland** [comment]
@mcastro-lqd oupps sorry missed that, will add, thankyou!
