### ISSUE TITLE
app/comment: voting comment only if in correct phase!

### ISSUE THREAD

**Issue by khamui** [liqd/zt-app#90]
Given user wants to vote
And is authenticated
And phase allows to vote
Then only then it is allowed to be voted
Otherwise voting (up and down) is disabled

Note: similar to vote idea

**Comment by fuzzylogic2000** [comment]
I think for comments, the voting is allowed when the commenting is allowed. But we still have to make sure that the buttons are disabled dependend on the idea

**Comment by khamui** [comment]
Closing this, because voting of comments is not implemented on the app, yet!
