### ISSUE TITLE
21-16 - Design Comments

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/zt-app#94]
Hey, 

I just added some screenshots to this pdf with comments. Since most of the things are about styling, I thought it would be easier to put everything in one .pdf, would that be ok? If you prefer, I can also write an issue for each comment. 

Also, my emulator was a bit crazy today so some of the stuff might be because of my emulator. 

[210817-zt-first-testing.pdf](https://github.com/liqd/zt-app/files/6999132/210817-zt-first-testing.pdf)

**Comment by khamui** [comment]
@mcastro-lqd thanks for putting all glitches together.
I guess together with @hello-kathi and @lthueer we should go through this PDF and consolidate and extract and then also prioritize these issues?

**Comment by lthueer** [comment]
We can definitely do that! In my opinion this is the prio list, as some of the comments @mcastro-lqd made are already in stories or fixed:

2) back button
10) fonts
4) a+ blue branding
6) centered text (delete idea)
3) reorder image button (for me the button disappeared completely)
8) spacing when cancel menu
1) error message (password)

will be solved with other workflows
9) rating colours: is part of the vote on ideas story (current sprint)
7) edit ideas - was not developed yet (pokered story in backlog)
5) description text --> we have a story for that pokered

Feel free to change the order @hello-kathi !
We can also meet to discuss these issues if you like @khamui =)

**Comment by khamui** [comment]
cool! thanks for the prompt prioritising. Are there any items that needs to be done as part of the current app sprint?

**Comment by hello-kathi** [comment]
I would say we will take it to next Sprintplanning and then have   a look about prior with all the other stuff.
What do you think?

**Comment by khamui** [comment]
sounds good 🤝

**Comment by lthueer** [comment]
splitted up in different stories. Closing this now!
